FROM nginx:alpine
RUN apk add --no-cache gettext
WORKDIR /usr/share/nginx/html
COPY . /usr/share/nginx/html
# Only rename if config.template.js is not present
RUN if [ ! -f config.template.js ]; then mv config.js config.template.js; fi
EXPOSE 80
CMD envsubst < config.template.js > config.js && nginx -g 'daemon off;'