# Use the official Nginx image
FROM nginx:latest

# Remove the default nginx static assets (optional)
RUN rm -rf /usr/share/nginx/html/*

# Copy your static files to the Nginx html directory
COPY ./Frontend /usr/share/nginx/html/Frontend

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
