# Use Node.js as base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY ./Backend .

# Expose the backend port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
